# SPDX-License-Identifier: GPL-2.0
kapi := arch/$(SRCARCH)/include/generated/asm
uapi := arch/$(SRCARCH)/include/generated/uapi/asm

_dummy := $(shell [ -d '$(uapi)' ] || mkdir -p '$(uapi)')	\
	  $(shell [ -d '$(kapi)' ] || mkdir -p '$(kapi)')

syshdr := $(srctree)/scripts/syscallhdr.sh

quiet_cmd_syshdr = SYSHDR  $@
      cmd_syshdr = $(CONFIG_SHELL) '$(syshdr)' '$<' '$@'	\
		   '$(syshdr_abis_$(basetarget))'		\
		   '$(syshdr_pfx_$(basetarget))'		\
		   '$(syshdr_offset_$(basetarget))'		\
		   '$(SRCARCH)'

quiet_cmd_systbl = SYSTBL  $@
      cmd_systbl = $(CONFIG_SHELL) '$(systbl)' '$<' '$@'	\
		   '$(systbl_abis_$(basetarget))'		\
		   '$(systbl_abi_$(basetarget))'		\
		   '$(systbl_offset_$(basetarget))'

$(uapi)/unistd_32.h: $(syscall) $(syshdr)
	$(call if_changed,syshdr)

$(uapi)/unistd_64.h: $(syscall) $(syshdr)
	$(call if_changed,syshdr)

$(kapi)/syscall_table_32.h: $(syscall) $(systbl)
	$(call if_changed,systbl)

$(kapi)/syscall_table_c32.h: $(syscall) $(systbl)
	$(call if_changed,systbl)

$(kapi)/syscall_table_64.h: $(syscall) $(systbl)
	$(call if_changed,systbl)

$(kapi)/syscall_table.h: $(syscall) $(systbl)
	$(call if_changed,systbl)

targets	+= $(uapisyshdr-y) $(kapisyshdr-y)

PHONY += all
all: $(addprefix $(uapi)/,$(uapisyshdr-y))
all: $(addprefix $(kapi)/,$(kapisyshdr-y))
	@:
